export default {
  SET_BUYER: "SET_BUYER",
  ADD_BUYER: "ADD_BUYER",
  UPDATE_BUYER: "UPDATE_BUYER",
  DELETE_BUYER: "DELETE_BUYER",
  SET_PACKAGE_TYPES: "SET_PACKAGE_TYPES",
  FETCH_BUYER: "FETCH_BUYER",
  FETCH_PACKAGE_TYPES: "FETCH_PACKAGE_TYPES",
};
